// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package pumpkin_plugin_common

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// Serialized text component as a postcard byte array.
// @deprecated Use the text-component resource from the text interface instead.
type RawTextComponent = []uint8

// A position in the world grid (integers).
type BlockPosition = witTypes.Tuple3[int32, int32, int32]

// A precise coordinate in the world (floats).
type Position = witTypes.Tuple3[float64, float64, float64]

const (
	HandLeft  uint8 = 0
	HandRight uint8 = 1
)

// Represents the hands of a player.
type Hand = uint8

const (
	GameModeSurvival  uint8 = 0
	GameModeCreative  uint8 = 1
	GameModeAdventure uint8 = 2
	GameModeSpectator uint8 = 3
)

// Represents the game modes available in Minecraft.
type GameMode = uint8

const (
	NamedColorBlack       uint8 = 0
	NamedColorDarkBlue    uint8 = 1
	NamedColorDarkGreen   uint8 = 2
	NamedColorDarkAqua    uint8 = 3
	NamedColorDarkRed     uint8 = 4
	NamedColorDarkPurple  uint8 = 5
	NamedColorGold        uint8 = 6
	NamedColorGray        uint8 = 7
	NamedColorDarkGray    uint8 = 8
	NamedColorBlue        uint8 = 9
	NamedColorGreen       uint8 = 10
	NamedColorAqua        uint8 = 11
	NamedColorRed         uint8 = 12
	NamedColorLightPurple uint8 = 13
	NamedColorYellow      uint8 = 14
	NamedColorWhite       uint8 = 15
)

// The 16 base Minecraft colors.
type NamedColor = uint8

// An RGB color represented by its red, green, and blue components.
type RgbColor struct {
	R uint8
	G uint8
	B uint8
}

// An ARGB color with alpha (transparency) channel.
type ArgbColor struct {
	A uint8
	R uint8
	G uint8
	B uint8
}

// Represents a stack of items with its type and count.
type ItemStack struct {
	// The unique registry key (e.g., "minecraft:diamond").
	RegistryKey string
	// The number of items in the stack.
	Count uint8
}

const (
	ClickTypeLeft        uint8 = 0
	ClickTypeRight       uint8 = 1
	ClickTypeShiftLeft   uint8 = 2
	ClickTypeShiftRight  uint8 = 3
	ClickTypeMiddle      uint8 = 4
	ClickTypeDrop        uint8 = 5
	ClickTypeControlDrop uint8 = 6
	ClickTypeDoubleClick uint8 = 7
	ClickTypeNumberKey   uint8 = 8
	ClickTypeUnknown     uint8 = 9
)

// Represents the type of click interaction in a GUI.
type ClickType = uint8

const (
	EntityPoseStanding    uint8 = 0
	EntityPoseFallFlying  uint8 = 1
	EntityPoseSleeping    uint8 = 2
	EntityPoseSwimming    uint8 = 3
	EntityPoseSpinAttack  uint8 = 4
	EntityPoseCrouching   uint8 = 5
	EntityPoseLongJumping uint8 = 6
	EntityPoseDying       uint8 = 7
	EntityPoseCroaking    uint8 = 8
	EntityPoseUsingTongue uint8 = 9
	EntityPoseSitting     uint8 = 10
	EntityPoseRoaring     uint8 = 11
	EntityPoseSniffing    uint8 = 12
	EntityPoseEmerging    uint8 = 13
	EntityPoseDigging     uint8 = 14
	EntityPoseSliding     uint8 = 15
	EntityPoseShooting    uint8 = 16
	EntityPoseInhaling    uint8 = 17
)

// Represents the various poses an entity can be in.
type EntityPose = uint8

const (
	LocaleAfZa    uint8 = 0
	LocaleArSa    uint8 = 1
	LocaleAstEs   uint8 = 2
	LocaleAzAz    uint8 = 3
	LocaleBaRu    uint8 = 4
	LocaleBar     uint8 = 5
	LocaleBeBy    uint8 = 6
	LocaleBgBg    uint8 = 7
	LocaleBrFr    uint8 = 8
	LocaleBrb     uint8 = 9
	LocaleBsBa    uint8 = 10
	LocaleCaEs    uint8 = 11
	LocaleCsCz    uint8 = 12
	LocaleCyGb    uint8 = 13
	LocaleDaDk    uint8 = 14
	LocaleDeAt    uint8 = 15
	LocaleDeCh    uint8 = 16
	LocaleDeDe    uint8 = 17
	LocaleElGr    uint8 = 18
	LocaleEnAu    uint8 = 19
	LocaleEnCa    uint8 = 20
	LocaleEnGb    uint8 = 21
	LocaleEnNz    uint8 = 22
	LocaleEnPt    uint8 = 23
	LocaleEnUd    uint8 = 24
	LocaleEnUs    uint8 = 25
	LocaleEnp     uint8 = 26
	LocaleEnws    uint8 = 27
	LocaleEoUy    uint8 = 28
	LocaleEsAr    uint8 = 29
	LocaleEsCl    uint8 = 30
	LocaleEsEc    uint8 = 31
	LocaleEsEs    uint8 = 32
	LocaleEsMx    uint8 = 33
	LocaleEsUy    uint8 = 34
	LocaleEsVe    uint8 = 35
	LocaleEsan    uint8 = 36
	LocaleEtEe    uint8 = 37
	LocaleEuEs    uint8 = 38
	LocaleFaIr    uint8 = 39
	LocaleFiFi    uint8 = 40
	LocaleFilPh   uint8 = 41
	LocaleFoFo    uint8 = 42
	LocaleFrCa    uint8 = 43
	LocaleFrFr    uint8 = 44
	LocaleFraDe   uint8 = 45
	LocaleFurIt   uint8 = 46
	LocaleFyNl    uint8 = 47
	LocaleGaIe    uint8 = 48
	LocaleGdGb    uint8 = 49
	LocaleGlEs    uint8 = 50
	LocaleHawUs   uint8 = 51
	LocaleHeIl    uint8 = 52
	LocaleHiIn    uint8 = 53
	LocaleHrHr    uint8 = 54
	LocaleHuHu    uint8 = 55
	LocaleHyAm    uint8 = 56
	LocaleIdId    uint8 = 57
	LocaleIgNg    uint8 = 58
	LocaleIoEn    uint8 = 59
	LocaleIsIs    uint8 = 60
	LocaleIsv     uint8 = 61
	LocaleItIt    uint8 = 62
	LocaleJaJp    uint8 = 63
	LocaleJboEn   uint8 = 64
	LocaleKaGe    uint8 = 65
	LocaleKkKz    uint8 = 66
	LocaleKnIn    uint8 = 67
	LocaleKoKr    uint8 = 68
	LocaleKsh     uint8 = 69
	LocaleKwGb    uint8 = 70
	LocaleLaLa    uint8 = 71
	LocaleLbLu    uint8 = 72
	LocaleLiLi    uint8 = 73
	LocaleLmo     uint8 = 74
	LocaleLoLa    uint8 = 75
	LocaleLolUs   uint8 = 76
	LocaleLtLt    uint8 = 77
	LocaleLvLv    uint8 = 78
	LocaleLzh     uint8 = 79
	LocaleMkMk    uint8 = 80
	LocaleMnMn    uint8 = 81
	LocaleMsMy    uint8 = 82
	LocaleMtMt    uint8 = 83
	LocaleNah     uint8 = 84
	LocaleNdsDe   uint8 = 85
	LocaleNlBe    uint8 = 86
	LocaleNlNl    uint8 = 87
	LocaleNnNo    uint8 = 88
	LocaleNoNo    uint8 = 89
	LocaleOcFr    uint8 = 90
	LocaleOvd     uint8 = 91
	LocalePlPl    uint8 = 92
	LocalePtBr    uint8 = 93
	LocalePtPt    uint8 = 94
	LocaleQyaAa   uint8 = 95
	LocaleRoRo    uint8 = 96
	LocaleRpr     uint8 = 97
	LocaleRuRu    uint8 = 98
	LocaleRyUa    uint8 = 99
	LocaleSahSah  uint8 = 100
	LocaleSeNo    uint8 = 101
	LocaleSkSk    uint8 = 102
	LocaleSlSi    uint8 = 103
	LocaleSoSo    uint8 = 104
	LocaleSqAl    uint8 = 105
	LocaleSrCs    uint8 = 106
	LocaleSrSp    uint8 = 107
	LocaleSvSe    uint8 = 108
	LocaleSxu     uint8 = 109
	LocaleSzl     uint8 = 110
	LocaleTaIn    uint8 = 111
	LocaleThTh    uint8 = 112
	LocaleTlPh    uint8 = 113
	LocaleTlhAa   uint8 = 114
	LocaleTok     uint8 = 115
	LocaleTrTr    uint8 = 116
	LocaleTtRu    uint8 = 117
	LocaleUkUa    uint8 = 118
	LocaleValEs   uint8 = 119
	LocaleVecIt   uint8 = 120
	LocaleViVn    uint8 = 121
	LocaleYiDe    uint8 = 122
	LocaleYoNg    uint8 = 123
	LocaleZhCn    uint8 = 124
	LocaleZhHk    uint8 = 125
	LocaleZhTw    uint8 = 126
	LocaleZlmArab uint8 = 127
)

// All Minecraft-supported locales.
type Locale = uint8
