// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package pumpkin_plugin_entity

import (
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_world"
)

type Entity = pumpkin_plugin_world.Entity
