// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package export_pumpkin_plugin_metadata

import (
	"github.com/Pumpkin-MC/pumpkin-api-go/api"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_metadata"
)

func GetMetadata() pumpkin_plugin_metadata.PluginMetadata {
	if instance := api.GetInstance(); instance != nil {
		return instance.Metadata()
	}
	return pumpkin_plugin_metadata.PluginMetadata{
		Name:         "unknown",
		Version:      "0.0.0",
		Authors:      nil,
		Description:  "No metadata",
		Dependencies: nil,
	}
}
