// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package pumpkin_plugin_scheduler

import ()

//go:wasmimport pumpkin:plugin/scheduler@0.1.0 schedule-delayed-task
func wasm_import_schedule_delayed_task(arg0 int32, arg1 int64) int32

func ScheduleDelayedTask(handlerId uint32, delayTicks uint64) uint32 {

	result := wasm_import_schedule_delayed_task(int32(handlerId), int64(delayTicks))
	return uint32(result)

}

//go:wasmimport pumpkin:plugin/scheduler@0.1.0 schedule-repeating-task
func wasm_import_schedule_repeating_task(arg0 int32, arg1 int64, arg2 int64) int32

func ScheduleRepeatingTask(handlerId uint32, delayTicks uint64, periodTicks uint64) uint32 {

	result := wasm_import_schedule_repeating_task(int32(handlerId), int64(delayTicks), int64(periodTicks))
	return uint32(result)

}

//go:wasmimport pumpkin:plugin/scheduler@0.1.0 cancel-task
func wasm_import_cancel_task(arg0 int32)

func CancelTask(taskId uint32) {

	wasm_import_cancel_task(int32(taskId))

}
