// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package wit_world

import (
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_command"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_context"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_event"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_server"
)

type Context = pumpkin_plugin_context.Context
type Event = pumpkin_plugin_event.Event
type ServerInstance = pumpkin_plugin_server.Server
type CommandSender = pumpkin_plugin_command.CommandSender
type ConsumedArgs = pumpkin_plugin_command.ConsumedArgs
type CommandError = pumpkin_plugin_command.CommandError
