// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package export_wit_world

import (
	"github.com/Pumpkin-MC/pumpkin-api-go/api"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_command"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_context"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_event"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_server"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_text"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

func InitPlugin() {
}

func OnLoad(ctx *pumpkin_plugin_context.Context) witTypes.Result[witTypes.Unit, string] {
	if instance := api.GetInstance(); instance != nil {
		instance.OnLoad(ctx)
	}
	return witTypes.Ok[witTypes.Unit, string](witTypes.Unit{})
}

func OnUnload(ctx *pumpkin_plugin_context.Context) witTypes.Result[witTypes.Unit, string] {
	if instance := api.GetInstance(); instance != nil {
		instance.OnUnload(ctx)
	}
	return witTypes.Ok[witTypes.Unit, string](witTypes.Unit{})
}

func HandleEvent(eventId uint32, server *pumpkin_plugin_server.Server, event pumpkin_plugin_event.Event) pumpkin_plugin_event.Event {
	if instance := api.GetInstance(); instance != nil {
		return instance.HandleEvent(eventId, server, event)
	}
	return event
}

func HandleCommand(commandId uint32, sender *pumpkin_plugin_command.CommandSender, server *pumpkin_plugin_server.Server, args *pumpkin_plugin_command.ConsumedArgs) witTypes.Result[int32, pumpkin_plugin_command.CommandError] {
	if instance := api.GetInstance(); instance != nil {
		result := instance.HandleCommand(commandId, sender, server, args)
		return witTypes.Ok[int32, pumpkin_plugin_command.CommandError](result)
	}
	return witTypes.Err[int32, pumpkin_plugin_command.CommandError](pumpkin_plugin_command.MakeCommandErrorCommandFailed(pumpkin_plugin_text.TextComponentText("Plugin instance not found")))
}

func HandleTask(handlerId uint32, server *pumpkin_plugin_server.Server) {
	// Not yet implemented in high-level API
}
