// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package wit_exports

import (
	"github.com/Pumpkin-MC/pumpkin-api-go/internal/exports/export_pumpkin_plugin_metadata"
	"github.com/Pumpkin-MC/pumpkin-api-go/internal/exports/export_wit_world"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_command"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_common"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_context"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_event"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_player"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_server"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_text"
	"github.com/Pumpkin-MC/pumpkin-api-go/pkg/pumpkin_plugin_world"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (24 + 12*4), 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport init-plugin
func wasm_export_wit_world_init_plugin() {

	export_wit_world.InitPlugin()

}

//go:wasmexport on-load
func wasm_export_wit_world_on_load(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.OnLoad(pumpkin_plugin_context.ContextFromOwnHandle(int32(uintptr(arg0))))

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_on-load
func wasm_export_post_return_wit_world_on_load(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport on-unload
func wasm_export_wit_world_on_unload(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.OnUnload(pumpkin_plugin_context.ContextFromOwnHandle(int32(uintptr(arg0))))

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_on-unload
func wasm_export_post_return_wit_world_on_unload(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport handle-event
func wasm_export_wit_world_handle_event(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	var variant pumpkin_plugin_event.Event
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 8))) {
	case 0:

		variant = pumpkin_plugin_event.MakeEventPlayerJoinEvent(pumpkin_plugin_event.PlayerJoinEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), pumpkin_plugin_text.TextComponentFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))) != 0)})

	case 1:

		variant = pumpkin_plugin_event.MakeEventPlayerLeaveEvent(pumpkin_plugin_event.PlayerLeaveEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), pumpkin_plugin_text.TextComponentFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))) != 0)})

	case 2:

		variant = pumpkin_plugin_event.MakeEventPlayerLoginEvent(pumpkin_plugin_event.PlayerLoginEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), pumpkin_plugin_text.TextComponentFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))) != 0)})

	case 3:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))
		result := make([]*pumpkin_plugin_player.Player, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))), index*4)

			result = append(result, pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 0))))))
		}

		variant = pumpkin_plugin_event.MakeEventPlayerChatEvent(pumpkin_plugin_event.PlayerChatEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value, result, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4)))) != 0)})

	case 4:
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerCommandSendEvent(pumpkin_plugin_event.PlayerCommandSendEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))) != 0)})

	case 5:
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerPermissionCheckEvent(pumpkin_plugin_event.PlayerPermissionCheckEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value1, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))) != 0)})

	case 6:

		variant = pumpkin_plugin_event.MakeEventPlayerMoveEvent(pumpkin_plugin_event.PlayerMoveEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), witTypes.Tuple3[float64, float64, float64]{*(*float64)(unsafe.Add(unsafe.Pointer(arg0), 24)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 32)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 40))}, witTypes.Tuple3[float64, float64, float64]{*(*float64)(unsafe.Add(unsafe.Pointer(arg0), 48)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 56)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 64))}, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 72))) != 0)})

	case 7:

		variant = pumpkin_plugin_event.MakeEventPlayerTeleportEvent(pumpkin_plugin_event.PlayerTeleportEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), witTypes.Tuple3[float64, float64, float64]{*(*float64)(unsafe.Add(unsafe.Pointer(arg0), 24)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 32)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 40))}, witTypes.Tuple3[float64, float64, float64]{*(*float64)(unsafe.Add(unsafe.Pointer(arg0), 48)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 56)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 64))}, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 72))) != 0)})

	case 8:

		variant = pumpkin_plugin_event.MakeEventPlayerChangeWorldEvent(pumpkin_plugin_event.PlayerChangeWorldEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), pumpkin_plugin_world.WorldFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))), pumpkin_plugin_world.WorldFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 24))))), witTypes.Tuple3[float64, float64, float64]{*(*float64)(unsafe.Add(unsafe.Pointer(arg0), 32)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 40)), *(*float64)(unsafe.Add(unsafe.Pointer(arg0), 48))}, *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 56)), *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 60)), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 64))) != 0)})

	case 9:

		variant = pumpkin_plugin_event.MakeEventPlayerExpChangeEvent(pumpkin_plugin_event.PlayerExpChangeEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))})

	case 10:

		variant = pumpkin_plugin_event.MakeEventPlayerItemHeldEvent(pumpkin_plugin_event.PlayerItemHeldEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 21)))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 22))) != 0)})

	case 11:

		variant = pumpkin_plugin_event.MakeEventPlayerChangedMainHandEvent(pumpkin_plugin_event.PlayerChangedMainHandEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20))))})

	case 12:

		variant = pumpkin_plugin_event.MakeEventPlayerGamemodeChangeEvent(pumpkin_plugin_event.PlayerGamemodeChangeEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 21)))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 22))) != 0)})

	case 13:
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))
		value3 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerCustomPayloadEvent(pumpkin_plugin_event.PlayerCustomPayloadEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value2, value3})

	case 14:
		var option witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))) {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))

			option = witTypes.Some[string](value4)
		default:
			panic("unreachable")
		}
		value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4))))
		value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 6*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 7*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerFishEvent(pumpkin_plugin_event.PlayerFishEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), option, value5, value6, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 8*4))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (17 + 8*4))))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (20 + 8*4))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 8*4)))) != 0)})

	case 15:
		value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))
		value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerEggThrowEvent(pumpkin_plugin_event.PlayerEggThrowEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value7, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))) != 0), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (17 + 3*4))))), value8, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 6*4)))) != 0)})

	case 16:

		variant = pumpkin_plugin_event.MakeEventPlayerInteractUnknownEntityEvent(pumpkin_plugin_event.PlayerInteractUnknownEntityEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24)))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 25))) != 0)})

	case 17:
		var option9 witTypes.Option[witTypes.Tuple3[int32, int32, int32]]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))) {
		case 0:

			option9 = witTypes.None[witTypes.Tuple3[int32, int32, int32]]()
		case 1:

			option9 = witTypes.Some[witTypes.Tuple3[int32, int32, int32]](witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 28)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 32)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 36))})
		default:
			panic("unreachable")
		}
		value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 1*4))))

		variant = pumpkin_plugin_event.MakeEventPlayerInteractEvent(pumpkin_plugin_event.PlayerInteractEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20)))), option9, value10, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 2*4)))) != 0)})

	case 18:

		variant = pumpkin_plugin_event.MakeEventPlayerToggleSneakEvent(pumpkin_plugin_event.PlayerToggleSneakEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 21))) != 0)})

	case 19:

		variant = pumpkin_plugin_event.MakeEventPlayerToggleFlightEvent(pumpkin_plugin_event.PlayerToggleFlightEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 21))) != 0)})

	case 20:

		variant = pumpkin_plugin_event.MakeEventPlayerToggleSprintEvent(pumpkin_plugin_event.PlayerToggleSprintEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 21))) != 0)})

	case 21:
		var option12 witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))) {
		case 0:

			option12 = witTypes.None[string]()
		case 1:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))

			option12 = witTypes.Some[string](value11)
		default:
			panic("unreachable")
		}
		var option14 witTypes.Option[pumpkin_plugin_common.ItemStack]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 4*4)))) {
		case 0:

			option14 = witTypes.None[pumpkin_plugin_common.ItemStack]()
		case 1:
			value13 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 6*4))))

			option14 = witTypes.Some[pumpkin_plugin_common.ItemStack](pumpkin_plugin_common.ItemStack{value13, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 7*4)))))})
		default:
			panic("unreachable")
		}
		var option16 witTypes.Option[pumpkin_plugin_common.ItemStack]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 8*4)))) {
		case 0:

			option16 = witTypes.None[pumpkin_plugin_common.ItemStack]()
		case 1:
			value15 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 9*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 10*4))))

			option16 = witTypes.Some[pumpkin_plugin_common.ItemStack](pumpkin_plugin_common.ItemStack{value15, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 11*4)))))})
		default:
			panic("unreachable")
		}

		variant = pumpkin_plugin_event.MakeEventInventoryClickEvent(pumpkin_plugin_event.InventoryClickEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), option12, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4))))), int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (18 + 4*4))))), int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (20 + 4*4))))), option14, option16, *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 12*4))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (28 + 12*4)))) != 0)})

	case 22:
		var option18 witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))) {
		case 0:

			option18 = witTypes.None[string]()
		case 1:
			value17 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))

			option18 = witTypes.Some[string](value17)
		default:
			panic("unreachable")
		}

		variant = pumpkin_plugin_event.MakeEventInventoryCloseEvent(pumpkin_plugin_event.InventoryCloseEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), option18})

	case 23:

		variant = pumpkin_plugin_event.MakeEventBlockRedstoneEvent(pumpkin_plugin_event.BlockRedstoneEventData{pumpkin_plugin_world.WorldFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 20)))), witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 24)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 28)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 32))}, *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 36)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 40)), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 44))) != 0)})

	case 24:
		var option19 witTypes.Option[*pumpkin_plugin_player.Player]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 16))) {
		case 0:

			option19 = witTypes.None[*pumpkin_plugin_player.Player]()
		case 1:

			option19 = witTypes.Some[*pumpkin_plugin_player.Player](pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))))
		default:
			panic("unreachable")
		}
		value20 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 1*4))))

		variant = pumpkin_plugin_event.MakeEventBlockBreakEvent(pumpkin_plugin_event.BlockBreakEventData{option19, value20, witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 2*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (28 + 2*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (32 + 2*4)))}, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (36 + 2*4)))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 2*4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (41 + 2*4)))) != 0)})

	case 25:
		value21 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4))))
		value22 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))

		variant = pumpkin_plugin_event.MakeEventBlockBurnEvent(pumpkin_plugin_event.BlockBurnEventData{value21, value22, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4)))) != 0)})

	case 26:
		value23 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4))))
		value24 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 3*4))))

		variant = pumpkin_plugin_event.MakeEventBlockCanBuildEvent(pumpkin_plugin_event.BlockCanBuildEventData{value23, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))) != 0), pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (20 + 2*4)))))), value24, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 4*4)))) != 0)})

	case 27:
		value25 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))
		value26 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4))))

		variant = pumpkin_plugin_event.MakeEventBlockGrowEvent(pumpkin_plugin_event.BlockGrowEventData{pumpkin_plugin_world.WorldFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value25, uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4))))), value26, uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 6*4))))), witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (20 + 6*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 6*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (28 + 6*4)))}, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (32 + 6*4)))) != 0)})

	case 28:
		value27 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4))))
		value28 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4))))

		variant = pumpkin_plugin_event.MakeEventBlockPlaceEvent(pumpkin_plugin_event.BlockPlaceEventData{pumpkin_plugin_player.PlayerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), value27, value28, witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (20 + 5*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 5*4)))}, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (28 + 5*4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (29 + 5*4)))) != 0)})

	case 29:
		value29 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 1*4))))

		variant = pumpkin_plugin_event.MakeEventServerCommandEvent(pumpkin_plugin_event.ServerCommandEventData{value29, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))) != 0)})

	case 30:

		variant = pumpkin_plugin_event.MakeEventSpawnChangeEvent(pumpkin_plugin_event.SpawnChangeEventData{pumpkin_plugin_world.WorldFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 24)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 28))}, *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 32)), *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 36)), witTypes.Tuple3[int32, int32, int32]{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 40)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 44)), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), 48))}, *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 52)), *(*float32)(unsafe.Add(unsafe.Pointer(arg0), 56))})

	case 31:

		variant = pumpkin_plugin_event.MakeEventServerBroadcastEvent(pumpkin_plugin_event.ServerBroadcastEventData{pumpkin_plugin_text.TextComponentFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 16))))), pumpkin_plugin_text.TextComponentFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 20))))), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 24))) != 0)})

	default:
		panic("unreachable")
	}
	witRuntime.Unpin()
	result30 := export_wit_world.HandleEvent(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 0))), pumpkin_plugin_server.ServerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 4))))), variant)

	switch result30.Tag() {
	case pumpkin_plugin_event.EventPlayerJoinEvent:
		payload := result30.PlayerJoinEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).JoinMessage).TakeHandle()
		var result31 int32
		if (payload).Cancelled {
			result31 = 1
		} else {
			result31 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(result31)

	case pumpkin_plugin_event.EventPlayerLeaveEvent:
		payload := result30.PlayerLeaveEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).LeaveMessage).TakeHandle()
		var result32 int32
		if (payload).Cancelled {
			result32 = 1
		} else {
			result32 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(result32)

	case pumpkin_plugin_event.EventPlayerLoginEvent:
		payload := result30.PlayerLoginEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(2))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).KickMessage).TakeHandle()
		var result33 int32
		if (payload).Cancelled {
			result33 = 1
		} else {
			result33 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(result33)

	case pumpkin_plugin_event.EventPlayerChatEvent:
		payload := result30.PlayerChatEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(3))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf8 := unsafe.Pointer(unsafe.StringData((payload).Message))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).Message)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf8)))
		slice := (payload).Recipients
		length := uint32(len(slice))
		result34 := witRuntime.Allocate(pinner, uintptr(length*4), 4)
		for index, element := range slice {
			base := unsafe.Add(result34, index*4)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = (element).TakeHandle()

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uintptr(uintptr(result34)))
		var result35 int32
		if (payload).Cancelled {
			result35 = 1
		} else {
			result35 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 5*4))) = int8(result35)

	case pumpkin_plugin_event.EventPlayerCommandSendEvent:
		payload := result30.PlayerCommandSendEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(4))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf836 := unsafe.Pointer(unsafe.StringData((payload).Command))
		pinner.Pin(utf836)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).Command)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf836)))
		var result37 int32
		if (payload).Cancelled {
			result37 = 1
		} else {
			result37 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = int8(result37)

	case pumpkin_plugin_event.EventPlayerPermissionCheckEvent:
		payload := result30.PlayerPermissionCheckEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(5))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf838 := unsafe.Pointer(unsafe.StringData((payload).Permission))
		pinner.Pin(utf838)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).Permission)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf838)))
		var result39 int32
		if (payload).PermissionResult {
			result39 = 1
		} else {
			result39 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = int8(result39)

	case pumpkin_plugin_event.EventPlayerMoveEvent:
		payload := result30.PlayerMoveEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(6))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = ((payload).FromPosition).F0
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = ((payload).FromPosition).F1
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = ((payload).FromPosition).F2
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = ((payload).ToPosition).F0
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 48)) = ((payload).ToPosition).F1
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 56)) = ((payload).ToPosition).F2
		var result40 int32
		if (payload).Cancelled {
			result40 = 1
		} else {
			result40 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 64)) = int8(result40)

	case pumpkin_plugin_event.EventPlayerTeleportEvent:
		payload := result30.PlayerTeleportEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(7))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = ((payload).FromPosition).F0
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = ((payload).FromPosition).F1
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = ((payload).FromPosition).F2
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = ((payload).ToPosition).F0
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 48)) = ((payload).ToPosition).F1
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 56)) = ((payload).ToPosition).F2
		var result41 int32
		if (payload).Cancelled {
			result41 = 1
		} else {
			result41 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 64)) = int8(result41)

	case pumpkin_plugin_event.EventPlayerChangeWorldEvent:
		payload := result30.PlayerChangeWorldEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(8))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).PreviousWorld).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = ((payload).NewWorld).TakeHandle()
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = ((payload).Position).F0
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = ((payload).Position).F1
		*(*float64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = ((payload).Position).F2
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 48)) = (payload).Yaw
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 52)) = (payload).Pitch
		var result42 int32
		if (payload).Cancelled {
			result42 = 1
		} else {
			result42 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 56)) = int8(result42)

	case pumpkin_plugin_event.EventPlayerExpChangeEvent:
		payload := result30.PlayerExpChangeEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(9))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = (payload).Amount

	case pumpkin_plugin_event.EventPlayerItemHeldEvent:
		payload := result30.PlayerItemHeldEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(10))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(int32((payload).PreviousSlot))
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 13)) = int8(int32((payload).NewSlot))
		var result43 int32
		if (payload).Cancelled {
			result43 = 1
		} else {
			result43 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 14)) = int8(result43)

	case pumpkin_plugin_event.EventPlayerChangedMainHandEvent:
		payload := result30.PlayerChangedMainHandEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(11))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(int32((payload).MainHand))

	case pumpkin_plugin_event.EventPlayerGamemodeChangeEvent:
		payload := result30.PlayerGamemodeChangeEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(12))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(int32((payload).PreviousGamemode))
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 13)) = int8(int32((payload).NewGamemode))
		var result44 int32
		if (payload).Cancelled {
			result44 = 1
		} else {
			result44 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 14)) = int8(result44)

	case pumpkin_plugin_event.EventPlayerCustomPayloadEvent:
		payload := result30.PlayerCustomPayloadEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(13))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf845 := unsafe.Pointer(unsafe.StringData((payload).Channel))
		pinner.Pin(utf845)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).Channel)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf845)))
		data := unsafe.Pointer(unsafe.SliceData((payload).Data))
		pinner.Pin(data)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uint32(len((payload).Data)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uintptr(uintptr(data)))

	case pumpkin_plugin_event.EventPlayerFishEvent:
		payload := result30.PlayerFishEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(14))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()

		switch (payload).CaughtUuid.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).CaughtUuid.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(1))
			utf846 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf846)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uintptr(uintptr(utf846)))

		default:
			panic("unreachable")
		}
		utf847 := unsafe.Pointer(unsafe.StringData((payload).CaughtType))
		pinner.Pin(utf847)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 5*4))) = uint32(uint32(len((payload).CaughtType)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uintptr(uintptr(utf847)))
		utf848 := unsafe.Pointer(unsafe.StringData((payload).HookUuid))
		pinner.Pin(utf848)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 7*4))) = uint32(uint32(len((payload).HookUuid)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 6*4))) = uint32(uintptr(uintptr(utf848)))
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 8*4))) = int8(int32((payload).State))
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 + 8*4))) = int8(int32((payload).Hand))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 8*4))) = (payload).ExpToDrop
		var result49 int32
		if (payload).Cancelled {
			result49 = 1
		} else {
			result49 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 8*4))) = int8(result49)

	case pumpkin_plugin_event.EventPlayerEggThrowEvent:
		payload := result30.PlayerEggThrowEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(15))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf850 := unsafe.Pointer(unsafe.StringData((payload).EggUuid))
		pinner.Pin(utf850)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).EggUuid)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf850)))
		var result51 int32
		if (payload).Hatching {
			result51 = 1
		} else {
			result51 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = int8(result51)
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 + 3*4))) = int8(int32((payload).NumHatches))
		utf852 := unsafe.Pointer(unsafe.StringData((payload).HatchingType))
		pinner.Pin(utf852)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 5*4))) = uint32(uint32(len((payload).HatchingType)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uintptr(uintptr(utf852)))
		var result53 int32
		if (payload).Cancelled {
			result53 = 1
		} else {
			result53 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 6*4))) = int8(result53)

	case pumpkin_plugin_event.EventPlayerInteractUnknownEntityEvent:
		payload := result30.PlayerInteractUnknownEntityEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(16))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = (payload).EntityId
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(int32((payload).Action))
		var result54 int32
		if (payload).Cancelled {
			result54 = 1
		} else {
			result54 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 17)) = int8(result54)

	case pumpkin_plugin_event.EventPlayerInteractEvent:
		payload := result30.PlayerInteractEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(17))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(int32((payload).Action))

		switch (payload).ClickedPos.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).ClickedPos.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(int32(1))
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 20)) = (payload).F0
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = (payload).F1
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 28)) = (payload).F2

		default:
			panic("unreachable")
		}
		utf855 := unsafe.Pointer(unsafe.StringData((payload).Block))
		pinner.Pin(utf855)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (32 + 1*4))) = uint32(uint32(len((payload).Block)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = uint32(uintptr(uintptr(utf855)))
		var result56 int32
		if (payload).Cancelled {
			result56 = 1
		} else {
			result56 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (32 + 2*4))) = int8(result56)

	case pumpkin_plugin_event.EventPlayerToggleSneakEvent:
		payload := result30.PlayerToggleSneakEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(18))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		var result57 int32
		if (payload).IsSneaking {
			result57 = 1
		} else {
			result57 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(result57)
		var result58 int32
		if (payload).Cancelled {
			result58 = 1
		} else {
			result58 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 13)) = int8(result58)

	case pumpkin_plugin_event.EventPlayerToggleFlightEvent:
		payload := result30.PlayerToggleFlightEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(19))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		var result59 int32
		if (payload).IsFlying {
			result59 = 1
		} else {
			result59 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(result59)
		var result60 int32
		if (payload).Cancelled {
			result60 = 1
		} else {
			result60 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 13)) = int8(result60)

	case pumpkin_plugin_event.EventPlayerToggleSprintEvent:
		payload := result30.PlayerToggleSprintEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(20))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		var result61 int32
		if (payload).IsSprinting {
			result61 = 1
		} else {
			result61 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int8(result61)
		var result62 int32
		if (payload).Cancelled {
			result62 = 1
		} else {
			result62 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 13)) = int8(result62)

	case pumpkin_plugin_event.EventInventoryClickEvent:
		payload := result30.InventoryClickEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(21))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()

		switch (payload).WindowType.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).WindowType.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(1))
			utf863 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf863)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uintptr(uintptr(utf863)))

		default:
			panic("unreachable")
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = int8(int32((payload).ClickType))
		*(*int16)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 + 4*4))) = int16(int32((payload).Slot))
		*(*int16)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 4*4))) = int16(int32((payload).RawSlot))

		switch (payload).ClickedItem.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 4*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).ClickedItem.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 4*4))) = int8(int32(1))
			utf864 := unsafe.Pointer(unsafe.StringData((payload).RegistryKey))
			pinner.Pin(utf864)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 6*4))) = uint32(uint32(len((payload).RegistryKey)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 5*4))) = uint32(uintptr(uintptr(utf864)))
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 7*4))) = int8(int32((payload).Count))

		default:
			panic("unreachable")
		}

		switch (payload).Cursor.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 8*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).Cursor.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 8*4))) = int8(int32(1))
			utf865 := unsafe.Pointer(unsafe.StringData((payload).RegistryKey))
			pinner.Pin(utf865)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 10*4))) = uint32(uint32(len((payload).RegistryKey)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 9*4))) = uint32(uintptr(uintptr(utf865)))
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 11*4))) = int8(int32((payload).Count))

		default:
			panic("unreachable")
		}
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 12*4))) = (payload).HotbarButton
		var result66 int32
		if (payload).Cancelled {
			result66 = 1
		} else {
			result66 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (20 + 12*4))) = int8(result66)

	case pumpkin_plugin_event.EventInventoryCloseEvent:
		payload := result30.InventoryCloseEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(22))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()

		switch (payload).WindowType.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).WindowType.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = int8(int32(1))
			utf867 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf867)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uintptr(uintptr(utf867)))

		default:
			panic("unreachable")
		}

	case pumpkin_plugin_event.EventBlockRedstoneEvent:
		payload := result30.BlockRedstoneEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(23))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).TargetWorld).TakeHandle()
		*(*int16)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = int16(int32((payload).StateId))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = ((payload).BlockPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 20)) = ((payload).BlockPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = ((payload).BlockPosition).F2
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 28)) = (payload).OldCurrent
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = (payload).NewCurrent
		var result68 int32
		if (payload).Cancelled {
			result68 = 1
		} else {
			result68 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 36)) = int8(result68)

	case pumpkin_plugin_event.EventBlockBreakEvent:
		payload := result30.BlockBreakEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(24))

		switch (payload).Player.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).Player.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(1))
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = (payload).TakeHandle()

		default:
			panic("unreachable")
		}
		utf869 := unsafe.Pointer(unsafe.StringData((payload).Block))
		pinner.Pin(utf869)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).Block)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf869)))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = ((payload).BlockPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (20 + 2*4))) = ((payload).BlockPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (24 + 2*4))) = ((payload).BlockPosition).F2
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (28 + 2*4))) = int32((payload).Exp)
		var result70 int32
		if (payload).ShouldDrop {
			result70 = 1
		} else {
			result70 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (32 + 2*4))) = int8(result70)
		var result71 int32
		if (payload).Cancelled {
			result71 = 1
		} else {
			result71 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (33 + 2*4))) = int8(result71)

	case pumpkin_plugin_event.EventBlockBurnEvent:
		payload := result30.BlockBurnEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(25))
		utf872 := unsafe.Pointer(unsafe.StringData((payload).IgnitingBlock))
		pinner.Pin(utf872)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uint32(len((payload).IgnitingBlock)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = uint32(uintptr(uintptr(utf872)))
		utf873 := unsafe.Pointer(unsafe.StringData((payload).Block))
		pinner.Pin(utf873)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uint32(len((payload).Block)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uintptr(uintptr(utf873)))
		var result74 int32
		if (payload).Cancelled {
			result74 = 1
		} else {
			result74 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = int8(result74)

	case pumpkin_plugin_event.EventBlockCanBuildEvent:
		payload := result30.BlockCanBuildEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(26))
		utf875 := unsafe.Pointer(unsafe.StringData((payload).BlockToBuild))
		pinner.Pin(utf875)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uint32(len((payload).BlockToBuild)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = uint32(uintptr(uintptr(utf875)))
		var result76 int32
		if (payload).Buildable {
			result76 = 1
		} else {
			result76 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = int8(result76)
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 2*4))) = ((payload).Player).TakeHandle()
		utf877 := unsafe.Pointer(unsafe.StringData((payload).Block))
		pinner.Pin(utf877)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 3*4))) = uint32(uint32(len((payload).Block)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = uint32(uintptr(uintptr(utf877)))
		var result78 int32
		if (payload).Cancelled {
			result78 = 1
		} else {
			result78 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 4*4))) = int8(result78)

	case pumpkin_plugin_event.EventBlockGrowEvent:
		payload := result30.BlockGrowEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(27))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).TargetWorld).TakeHandle()
		utf879 := unsafe.Pointer(unsafe.StringData((payload).OldBlock))
		pinner.Pin(utf879)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).OldBlock)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf879)))
		*(*int16)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = int16(int32((payload).OldStateId))
		utf880 := unsafe.Pointer(unsafe.StringData((payload).NewBlock))
		pinner.Pin(utf880)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 5*4))) = uint32(uint32(len((payload).NewBlock)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uintptr(uintptr(utf880)))
		*(*int16)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 6*4))) = int16(int32((payload).NewStateId))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 6*4))) = ((payload).BlockPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 6*4))) = ((payload).BlockPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (20 + 6*4))) = ((payload).BlockPosition).F2
		var result81 int32
		if (payload).Cancelled {
			result81 = 1
		} else {
			result81 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (24 + 6*4))) = int8(result81)

	case pumpkin_plugin_event.EventBlockPlaceEvent:
		payload := result30.BlockPlaceEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(28))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Player).TakeHandle()
		utf882 := unsafe.Pointer(unsafe.StringData((payload).BlockPlaced))
		pinner.Pin(utf882)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).BlockPlaced)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf882)))
		utf883 := unsafe.Pointer(unsafe.StringData((payload).BlockPlacedAgainst))
		pinner.Pin(utf883)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uint32(len((payload).BlockPlacedAgainst)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uintptr(uintptr(utf883)))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 5*4))) = ((payload).BlockPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 5*4))) = ((payload).BlockPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 5*4))) = ((payload).BlockPosition).F2
		var result84 int32
		if (payload).CanBuild {
			result84 = 1
		} else {
			result84 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (20 + 5*4))) = int8(result84)
		var result85 int32
		if (payload).Cancelled {
			result85 = 1
		} else {
			result85 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (21 + 5*4))) = int8(result85)

	case pumpkin_plugin_event.EventServerCommandEvent:
		payload := result30.ServerCommandEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(29))
		utf886 := unsafe.Pointer(unsafe.StringData((payload).Command))
		pinner.Pin(utf886)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uint32(len((payload).Command)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = uint32(uintptr(uintptr(utf886)))
		var result87 int32
		if (payload).Cancelled {
			result87 = 1
		} else {
			result87 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = int8(result87)

	case pumpkin_plugin_event.EventSpawnChangeEvent:
		payload := result30.SpawnChangeEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(30))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).TargetWorld).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).PreviousPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = ((payload).PreviousPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 20)) = ((payload).PreviousPosition).F2
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = (payload).PreviousYaw
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 28)) = (payload).PreviousPitch
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = ((payload).NewPosition).F0
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 36)) = ((payload).NewPosition).F1
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = ((payload).NewPosition).F2
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 44)) = (payload).NewYaw
		*(*float32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 48)) = (payload).NewPitch

	case pumpkin_plugin_event.EventServerBroadcastEvent:
		payload := result30.ServerBroadcastEvent()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(31))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = ((payload).Message).TakeHandle()
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 12)) = ((payload).Sender).TakeHandle()
		var result88 int32
		if (payload).Cancelled {
			result88 = 1
		} else {
			result88 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = int8(result88)

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_handle-event
func wasm_export_post_return_wit_world_handle_event(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport handle-command
func wasm_export_wit_world_handle_command(arg0 int32, arg1 int32, arg2 int32, arg3 int32) uintptr {

	pinner := &syncExportPinner
	result := export_wit_world.HandleCommand(uint32(arg0), pumpkin_plugin_command.CommandSenderFromOwnHandle(int32(uintptr(arg1))), pumpkin_plugin_server.ServerFromOwnHandle(int32(uintptr(arg2))), pumpkin_plugin_command.ConsumedArgsFromOwnHandle(int32(uintptr(arg3))))

	switch result.Tag() {
	case witTypes.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = payload

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

		switch payload.Tag() {
		case pumpkin_plugin_command.CommandErrorInvalidConsumption:
			payload := payload.InvalidConsumption()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(0))

			switch payload.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := payload.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = int8(int32(1))
				utf8 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf8)
				*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uintptr(uintptr(utf8)))

			default:
				panic("unreachable")
			}

		case pumpkin_plugin_command.CommandErrorInvalidRequirement:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(1))

		case pumpkin_plugin_command.CommandErrorPermissionDenied:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(2))

		case pumpkin_plugin_command.CommandErrorCommandFailed:
			payload := payload.CommandFailed()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = (payload).TakeHandle()

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_handle-command
func wasm_export_post_return_wit_world_handle_command(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport handle-task
func wasm_export_wit_world_handle_task(arg0 int32, arg1 int32) {

	export_wit_world.HandleTask(uint32(arg0), pumpkin_plugin_server.ServerFromOwnHandle(int32(uintptr(arg1))))

}

//go:wasmexport pumpkin:plugin/metadata@0.1.0#get-metadata
func wasm_export_pumpkin_plugin_metadata_get_metadata() uintptr {

	pinner := &syncExportPinner
	result := export_pumpkin_plugin_metadata.GetMetadata()
	utf8 := unsafe.Pointer(unsafe.StringData((result).Name))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len((result).Name)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData((result).Version))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((result).Version)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	slice := (result).Authors
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(2*4))
		utf81 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf81)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uintptr(uintptr(result2)))
	utf83 := unsafe.Pointer(unsafe.StringData((result).Description))
	pinner.Pin(utf83)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uint32(len((result).Description)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uintptr(uintptr(utf83)))
	slice5 := (result).Dependencies
	length7 := uint32(len(slice5))
	result6 := witRuntime.Allocate(pinner, uintptr(length7*(2*4)), 4)
	for index, element := range slice5 {
		base := unsafe.Add(result6, index*(2*4))
		utf84 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf84)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf84)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = uint32(length7)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = uint32(uintptr(uintptr(result6)))
	return exportReturnArea

}

//go:wasmexport cabi_post_pumpkin:plugin/metadata@0.1.0#get-metadata
func wasm_export_post_return_pumpkin_plugin_metadata_get_metadata(result uintptr) {
	syncExportPinner.Unpin()
}
