// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     pumpkin:plugin@0.1.0

package pumpkin_plugin_metadata

import ()

type PluginMetadata struct {
	// Name of the plugin.
	Name string
	// Plugin version (semver).
	Version string
	// Plugin authors.
	Authors []string
	// Short description of the plugin.
	Description string
	// Plugin dependencies.
	Dependencies []string
}
